server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-admin-password: test
        web-allow-others: true

logging:
  level:
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    root: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days