server:
  port: 8082

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cache:
    type: redis
    redis:
      time-to-live: 600000

  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-admin-password: test
        web-allow-others: true

  data:
    redis:
      timeout: 60000ms
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cache: TRACE
    root: INFO


springdoc:
  swagger-ui:
    path: /swagger-ui.html


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days