server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  h2:
#    console:
#      enabled: false
#      path: /h2-console
#      settings:
#        web-admin-password: test
#        web-allow-others: true



langchain4j:
  ollama:
    streaming-chat-model:
      base-url: http://localhost:11434
      model-name: llama3
    chat-model:
      base-url: http://localhost:11434   # where Ollama is running
      model-name: llama3                 # or mistral, codellama, etc.
logging:
  level:
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    root: info


springdoc:
  swagger-ui:
    path: /swagger-ui.html


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days